name: Build Python

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: docker  # Sollte zum Label 'docker:docker://node:20-bookworm' passen

    steps:
      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Python installieren (für Debian/Bookworm)
        run: |
          apt-get update
          apt-get install -y python3 python3-pip python3.11-venv
        
      - name: Virtuelle Umgebung erstellen
        run: |
          python3 -m venv venv
          source venv/bin/activate
          echo "VIRTUAL_ENV=venv" >> $GITHUB_ENV
          echo "$(pwd)/venv/bin" >> $GITHUB_PATH

      - name: Dependencies in venv installieren
        run: |
          source venv/bin/activate
          pip install -r requirments.txt

      - name: Binary bauen
        run: |
          nuitka --standalone Start-Ui.py

      - name: Upload
        uses: https://code.forgejo.org/actions/upload-artifact@v4
        with:
          name: bin
          path: Start-Ui.dist